name: Deploy Vite site to GitHub Pages 🚀

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Clean and install dependencies
        run: |
          rm -rf node_modules
          npm install

      - name: Ensure Vite is installed
        run: npm install vite --force

      - name: Fix permissions for vite
        run: chmod +x ./node_modules/.bin/vite

      - name: Build project
        run: npm run build

      - name: Create gh-pages branch if it doesn't exist
        run: |
          git config user.name "Minh Quan"
          git config user.email "minhquan4so9@gmail.com"
          git fetch origin
          if ! git rev-parse --verify origin/gh-pages; then
            git checkout --orphan gh-pages
            git reset --hard
            git commit --allow-empty -m "Initial commit on gh-pages"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/minhquanned/purus-internship-game.git gh-pages
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
